/*
 * @lc app=leetcode.cn id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.cn/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (66.19%)
 * Likes:    425
 * Dislikes: 0
 * Total Accepted:    175.3K
 * Total Submissions: 264.8K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * 
 * Example 1:
 * 
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * 
 * Example 2:
 * 
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 * 
 * 
 * Constraints:
 * 
 * 
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 * 
 * 
 */

public class _0389_FindTheDifference {
// @lc code=start
    class Solution {
        public char findTheDifference(String s, String t) {
            // xor string s and string t...
            char ch = t.charAt(0);
            for (int i = 0; i < s.length(); i++){
                ch ^= s.charAt(i) ^ t.charAt(i + 1);
            }
            return ch;
        }
    }
// @lc code=end
}

